#!/usr/bin/env bash
. "$ANYFORM_IMPL_DIR/common.sh"

outfile="$ANYFORM_OUTPUT_DIR/$ANYFORM_STAGE_NAME/output.txt"

function run_up() {
  echo "Cooking up the curry"
  echo "Oh no! Forgot the galangal!..." >&2

  local curry_type veggies
  curry_type="$(cat "$ANYFORM_CONFIG_JSON_FILE" | jq -r '.color')"
  veggies="$(cat "$ANYFORM_OUTPUT_DIR/shop/output.json" | jq -r '.vegetables | join(", ")' )"
  mkdir -p "$(dirname "$outfile")"
  echo "simmering $veggies in $curry_type curry" > "$outfile"

  echo "Curry is done"
}

function run_down() {
  rm -f "$outfile"
}

common_main "$@"

