#!/usr/bin/env bash
. "$ANYFORM_IMPL_DIR/common.sh"

outfile="$ANYFORM_STAGE_OUTPUT_DIR/output.txt"

function run_up() {
  # Force cook_curry to start after cook_rice so that tests have a predictable
  # order to check for.
  sleep 0.5
  echo "Cooking up the curry"
  sleep 0.1 # stderr and stdout can get reordered. See STDOUT_STDERR_ORDER_ISSUE
            # in other files for details.
  echo "Oh no! Forgot the galangal!..." >&2

  local curry_type veggies
  curry_type="$(cat "$ANYFORM_CONFIG_JSON_FILE" | jq -r '.color')"
  veggies="$(cat "$ANYFORM_OUTPUT_DIR/shop/output.json" | jq -r '.vegetables | join(", ")' )"
  echo "simmering $veggies in $curry_type curry" > "$outfile"

  echo "Curry is done"
}

function run_down() {
  rm -f "$outfile"
}

common_main "$@"

