#!/usr/bin/env bash
. "$ANYFORM_IMPL_DIR/common.sh"

outfile="$ANYFORM_STAGE_OUTPUT_DIR/output.json"

function run_up() {
  echo "Walking to the store"
  echo "Filling up the cart"

  sed 's/^    //g' <<EOF | jq > "$outfile"
    {
      "vegetables": ["eggplant", "lemongrass"],
      "rice": "jasmin"
    }
EOF

  echo "Pay for everything"
  echo "Head home"
}

function run_down() {
  echo '{}' > "$outfile"
}

common_main "$@"

