#!/usr/bin/env bash
. "$IMPL_DIR/common.sh"

outfile="$ANYFORM_OUTPUT_DIR/$ANYFORM_STAGE_NAME/output.json"

function run_up() {
  sed 's/^    //g' <<EOF > "$outfile"
    {
      vegetables: ['eggplant', 'lemongrass'],
      rice: 'jasmin',
    }
EOF
}

function run_down() {
  echo '{}' > "$outfile"
}

common_main "$@"

