#!/usr/bin/env bash
. "$ANYFORM_IMPL_DIR/common.sh"

outfile="$ANYFORM_OUTPUT_DIR/$ANYFORM_STAGE_NAME/output.json"

function run_up() {
  mkdir -p "$(dirname "$outfile")"
  sed 's/^    //g' <<EOF | jq > "$outfile"
    {
      "vegetables": ["eggplant", "lemongrass"],
      "rice": "jasmin"
    }
EOF
}

function run_down() {
  echo '{}' > "$outfile"
}

common_main "$@"

