#!/usr/bin/env bash
. "$IMPL_DIR/common.sh"

outfile="$ANYFORM_OUTPUT_DIR/$ANYFORM_STAGE_NAME/output.txt"

function run_up() {
  echo "boiling $(cat "$OUTPUT_DIR/shop" | jq .rice) rice" \
    > "$outfile"
}

function run_down() {
  rm -f "$outfile"
}

common_main "$@"

