#!/usr/bin/env bash
. "$ANYFORM_IMPL_DIR/common.sh"

outfile="$ANYFORM_STAGE_OUTPUT_DIR/output.txt"

function run_up() {
  echo "Cooking up the rice"

  echo "boiling $(cat "$ANYFORM_OUTPUT_DIR/shop/output.json" | jq .rice) rice" \
    > "$outfile"

  echo "Rice is done"
}

function run_down() {
  rm -f "$outfile"
}

common_main "$@"

