#!/usr/bin/env bash
. "$ANYFORM_IMPL_DIR/common.sh"

outfile="$ANYFORM_OUTPUT_DIR/nomnom.txt"

function run_up() {
  echo "Nom nom nom"

  mkdir -p "$(dirname "$outfile")"
  {
    echo "Eating a {{ .cfg.day }} night dinner prepped by:"
    {
      cat "$ANYFORM_OUTPUT_DIR/cook_rice/output.txt"
      cat "$ANYFORM_OUTPUT_DIR/cook_curry/output.txt"
    } | sed 's/^/  /g'
    # templating isn't needed here since we're in bash, but this is done here to
    # demonstrate the feature which is important in other languages (Terraform,
    # etc).
    echo "{{ .Env.USER }} says yum yum!"
  } > "$outfile"

  echo "Yum"
}

function run_down() {
  echo "Ignoring down is sometimes totally reasonable"
}

common_main "$@"

