
on:
  push:
    tags:
    - 'v*'

name: Build, Test, Release

jobs:
  build:
    name: Build, Test, Draft Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:

      - name: Setup machine
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -y update
          sudo apt-get -y install git curl make docker-ce

      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive

      - name: Cross compile in docker container
        run: |
          . activate.bash
          docker buildx create --name=buildcontainer --driver=docker-container --use --bootstrap
          echo "${{ secrets.GITHUB_TOKEN }}" |
            docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          CONTAINER_REGISTRY=ghcr.io/elevationtools \
            ANYFORM_VERSION="${{ github.ref_name }}" mako -C build github

      - name: Create release
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GH_REPO: "${{ github.repository }}"
        run: |
          gh release create --draft --verify-tag ${{ github.ref_name }} \
            ./build/genfiles/bin/anyform-*

